server:
  port: 9004
spring:
  profiles:
    active: mongo,commons
  application:
    name: livegoods-details
  redis: # 提供Redis配置
    host: 192.168.1.4
    port: 6379
    database: 0
eureka:
  instance:
    prefer-ip-address: true # 使用ip注册，不使用主机名
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://172.17.0.8:8761/eureka/  # 注册中心
      register-with-eureka: true
livegoods:
  details:
    imgMiddle: 'group1/M00/00/00/'