server:
  port: 9002
spring:
  application:
    name: livegoods-hot-product
  profiles:
    active: mongo,commons
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://172.17.0.4:8761/eureka/
      register-with-eureka: true