server:
  port: 9004
spring:
  profiles:
    active: mongo,commons
  application:
    name: livegoods-details
  redis: # 提供Redis配置
    host: 192.168.1.4
    port: 6379
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.4:8761/eureka/
#      defaultZone: http://127.0.0.1:8761/eureka/
      register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
livegoods:
  details:
    imgMiddle: 'group1/M00/00/00/'