server:
  port: 9008
spring:
  application:
    name: livegoods-order
  profiles:
    active: mongo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lcn?serverTimezone=Asia/Shanghai
    username: root
    password: ty123456
  redis:
    host: 192.168.1.4
tx-lcn:
  client:
    manager-address: 192.168.1.4:8070
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.4:8761/eureka/
  instance:
    prefer-ip-address: true